---
- name: Install Nginx
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Ensure Nginx is at the latest version
      apt:
       name: nginx
       state: latest
    - name: Make sure Nginx is running
      systemd:
        state: started
        name: nginx
  